[languages]

    [languages.php]
    Extension=".php"
    Cmd=["php","main.php"]
    [languages.php.images]
    "7.3"="php:7.3-alpine"
    "7.2"="php:7.2-alpine"
    "7.1"="php:7.1-alpine"
    "7.0"="php:7.0-alpine"
    "5.6"="php:5.6-alpine"

    [languages.golang]
    Extension=".go"
    Cmd=["go","run","main.go"]
    [languages.golang.images]
    "1.12"="golang:1.12-alpine"
    "1.11"="golang:1.11-alpine"

    [languages.python]
    Extension=".py"
    Cmd=["python","main.py"]
    [languages.python.images]
    "3.6"="python:3.6-alpine"
    "2.7"="python:2.7-alpine"

    [languages.c]
    Extension=".c"
    Cmd=["sh","-c","gcc -o main.out main.c && ./main.out"]
    [languages.c.images]
    "gcc:9"="gcc:9"

    [languages."c++"]
    Extension=".cpp"
    Cmd=["sh","-c","gcc main.cpp -lstdc++ -o main.out && ./main.out"]
    [languages."c++".images]
    "gcc:9"="gcc:9"

    [languages.ruby]
    Extension=".rb"
    Cmd=["ruby","main.rb"]
    [languages.ruby.images]
    "2.6"="ruby:2.6-alpine"

    [languages.java]
    Extension=".java"
    Cmd=["sh","-c","javac main.java && java Main"]
    [languages.java.images]
    "13"="openjdk:13-alpine"


[container]
#容器最大执行时间 单位s
MaxExcuteTime=20
#获取容器结果的最大字符串长度
MaxLogLength=500
#abs path
TemFilePath="/tmp/code-runner"
#容器前缀
ContainerNamePrefix="code-runner"
#network is none?
NetworkNone=false
    #容器限制
    [container.limit]
    #内存 单位m
    Memory=50
    #进程数
    PidsLimit=50
    #磁盘 m
    DiskQuota=10
    #cpu权重 相对其它容器
    CPUShares=1024
    #cpu 单位ms
    CPUPeriod=100
    #cpu 单位ms
    CPUQuota=200

[http]
#端口
Port=8080
#模式 debug release test
Mode=""


[docker]
#docker api version
ApiVersion=""