[languages]

    [languages.php]
    extension=".php"
    cmd=["php","main.php"]
    [languages.php.images]
    "7.3"="php:7.3-alpine"
    "7.2"="php:7.2-alpine"
    "7.1"="php:7.1-alpine"
    "7.0"="php:7.0-alpine"
    "5.6"="php:5.6-alpine"
    "default"="latest"

    [languages.golang]
    extension=".go"
    cmd=["go","run","main.go"]
    [languages.golang.images]
    "1.12"="golang:1.12-alpine"
    "1.11"="golang:1.11-alpine"
    "default"="latest"


[container]
#容器最大执行时间 单位s
MaxExcuteTime=20
#abs path
TemFilePath="/tmp/code-runner"
#容器前缀
ContainerNamePrefix="code-runner"
    #容器限制
    [container.limit]
    #内存 单位m
    Memory=50
    #进程数
    PidsLimit=50
    #磁盘 m
    DiskQuota=10
    #cpu权重 相对其它容器
    CPUShares=1024
    #cpu 单位ms
    CPUPeriod=100
    #cpu 单位ms
    CPUQuota=200

